kind: pipeline
name: default

steps:
- name: mytest
  image: openjdk:8
  commands:
    - java -version
    - echo $JAVA_HOME
    - whereis java



- name: test
  image: carvk/java_python:openjdk15_python38
  commands:
    - python --version
    - java -version
    - echo $JAVA_HOME
    - whereis java
    - pip install -r requirements.txt
    - pytest -v -s --browser=bs --runid=1