kind: pipeline
name: default

steps:
- name: mytest
  image: openjdk:8
  commands:
    - java -version
    - echo %JAVA_HOME%



- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest -v -s --browser=bs --runid=1