kind: pipeline
name: default

steps:
- name: mytest
  image: maven:3-jdk-10
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V



- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest -v -s --browser=bs --runid=1